// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixapoibuyumuuhamvost.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4YXBvaWJ1eXVtdXVoYW12b3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODcyNDIsImV4cCI6MjA3MDE2MzI0Mn0.O3g4Jh-t2BRnbP2qhqU4ZxXMpagKtBNX3H5z7eWgj8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});